// Generert av kjerne/scripts/bygg.ts fra classes.ts og elements.ts. Ikke rediger.
use crate::types::*;

pub static ELEMENTS: &[Element] = &[
    Element {
        tag: "fs-field",
        link: "https://fristil.sobernetics.no/components/field/",
        attributes: &[("invalid", Attribute::Flag), ("disabled", Attribute::Flag), ("optional", Attribute::Flag), ("required-marker", Attribute::Values(&["symbol", "text", "none"])), ("control-id", Attribute::Text), ("described-by", Attribute::Text)],
    },
    Element {
        tag: "fs-tabs",
        link: "https://fristil.sobernetics.no/components/tabs/",
        attributes: &[("server-controlled", Attribute::Flag)],
    },
    Element {
        tag: "fs-error-summary",
        link: "https://fristil.sobernetics.no/components/error-summary/",
        attributes: &[("data-autofocus", Attribute::Values(&["false"])), ("hidden", Attribute::Flag)],
    },
    Element {
        tag: "fs-popover",
        link: "https://fristil.sobernetics.no/components/popover/",
        attributes: &[("open", Attribute::Flag), ("placement", Attribute::Values(&["bottom-start", "bottom-end", "top-start", "top-end"])), ("server-controlled", Attribute::Flag)],
    },
    Element {
        tag: "fs-suggestion",
        link: "https://fristil.sobernetics.no/components/suggestion/",
        attributes: &[("prefiltered", Attribute::Flag), ("count-none", Attribute::Text), ("count-zero", Attribute::Text), ("count-one", Attribute::Text), ("count-two", Attribute::Text), ("count-few", Attribute::Text), ("count-many", Attribute::Text), ("count-other", Attribute::Text), ("server-controlled", Attribute::Flag)],
    },
    Element {
        tag: "fs-dialog",
        link: "https://fristil.sobernetics.no/components/dialog/",
        attributes: &[("open", Attribute::Flag), ("server-controlled", Attribute::Flag)],
    },
    Element {
        tag: "fs-toast",
        link: "https://fristil.sobernetics.no/components/toast/",
        attributes: &[("duration", Attribute::Number), ("label", Attribute::Text), ("close-label", Attribute::Text)],
    },
    Element {
        tag: "fs-session-timeout",
        link: "https://fristil.sobernetics.no/components/session-timeout/",
        attributes: &[("warn-at", Attribute::Number), ("expires-at", Attribute::Number)],
    },
    Element {
        tag: "fs-connection-status",
        link: "https://fristil.sobernetics.no/components/connection-status/",
        attributes: &[("offline-text", Attribute::Text), ("online-text", Attribute::Text)],
    },
];

pub static CLASSES: &[Class] = &[
    Class {
        name: "fs-accordion",
        title: "Accordion",
        link: "https://fristil.sobernetics.no/components/accordion/",
        attributes: &[("data-variant", ClassAttribute { values: &["plain"], default_value: Some("default") })],
    },
    Class {
        name: "fs-accordion__content",
        title: "Accordion",
        link: "https://fristil.sobernetics.no/components/accordion/",
        attributes: &[],
    },
    Class {
        name: "fs-alert",
        title: "Alert",
        link: "https://fristil.sobernetics.no/components/alert/",
        attributes: &[("data-color", ClassAttribute { values: &["info", "success", "warning", "danger"], default_value: None })],
    },
    Class {
        name: "fs-alert__title",
        title: "Alert",
        link: "https://fristil.sobernetics.no/components/alert/",
        attributes: &[],
    },
    Class {
        name: "fs-avatar",
        title: "Avatar",
        link: "https://fristil.sobernetics.no/components/avatar/",
        attributes: &[("data-variant", ClassAttribute { values: &["square"], default_value: Some("circle") }), ("data-size", ClassAttribute { values: &["small", "large"], default_value: Some("medium") })],
    },
    Class {
        name: "fs-avatar-stack",
        title: "Avatar",
        link: "https://fristil.sobernetics.no/components/avatar/",
        attributes: &[],
    },
    Class {
        name: "fs-badge",
        title: "Badge",
        link: "https://fristil.sobernetics.no/components/badge/",
        attributes: &[("data-color", ClassAttribute { values: &["success", "warning", "danger", "neutral"], default_value: Some("info") })],
    },
    Class {
        name: "fs-breadcrumbs",
        title: "Breadcrumbs",
        link: "https://fristil.sobernetics.no/components/breadcrumbs/",
        attributes: &[],
    },
    Class {
        name: "fs-button",
        title: "Button",
        link: "https://fristil.sobernetics.no/components/button/",
        attributes: &[("data-variant", ClassAttribute { values: &["secondary", "ghost", "danger"], default_value: Some("primary") })],
    },
    Class {
        name: "fs-card",
        title: "Card",
        link: "https://fristil.sobernetics.no/components/card/",
        attributes: &[("data-variant", ClassAttribute { values: &["filled"], default_value: Some("outline") })],
    },
    Class {
        name: "fs-card__title",
        title: "Card",
        link: "https://fristil.sobernetics.no/components/card/",
        attributes: &[],
    },
    Class {
        name: "fs-checkbox",
        title: "Checkbox",
        link: "https://fristil.sobernetics.no/components/checkbox/",
        attributes: &[("data-state", ClassAttribute { values: &["invalid", "success"], default_value: Some("default") })],
    },
    Class {
        name: "fs-checkbox-row",
        title: "Checkbox",
        link: "https://fristil.sobernetics.no/components/checkbox/",
        attributes: &[],
    },
    Class {
        name: "fs-divider",
        title: "Divider",
        link: "https://fristil.sobernetics.no/components/divider/",
        attributes: &[("data-variant", ClassAttribute { values: &["subtle", "strong"], default_value: Some("default") })],
    },
    Class {
        name: "fs-error-text",
        title: "Error Text",
        link: "https://fristil.sobernetics.no/components/error-text/",
        attributes: &[("data-variant", ClassAttribute { values: &["warning"], default_value: Some("error") })],
    },
    Class {
        name: "fs-fieldset",
        title: "Fieldset",
        link: "https://fristil.sobernetics.no/components/fieldset/",
        attributes: &[("data-state", ClassAttribute { values: &["invalid", "success"], default_value: Some("default") })],
    },
    Class {
        name: "fs-legend",
        title: "Fieldset",
        link: "https://fristil.sobernetics.no/components/fieldset/",
        attributes: &[("data-required", ClassAttribute { values: &["symbol", "text"], default_value: None })],
    },
    Class {
        name: "fs-file-upload",
        title: "File Upload",
        link: "https://fristil.sobernetics.no/components/file-upload/",
        attributes: &[("data-state", ClassAttribute { values: &["invalid", "success"], default_value: Some("default") })],
    },
    Class {
        name: "fs-file-upload-list",
        title: "File Upload",
        link: "https://fristil.sobernetics.no/components/file-upload/",
        attributes: &[],
    },
    Class {
        name: "fs-heading",
        title: "Heading",
        link: "https://fristil.sobernetics.no/components/heading/",
        attributes: &[("data-size", ClassAttribute { values: &["xs", "s", "m", "xl", "mega"], default_value: Some("l") })],
    },
    Class {
        name: "fs-help-text",
        title: "Help Text",
        link: "https://fristil.sobernetics.no/components/help-text/",
        attributes: &[("data-variant", ClassAttribute { values: &["strong", "success", "warning"], default_value: Some("muted") })],
    },
    Class {
        name: "fs-input",
        title: "Input",
        link: "https://fristil.sobernetics.no/components/input/",
        attributes: &[("data-state", ClassAttribute { values: &["invalid", "success"], default_value: Some("default") }), ("data-variant", ClassAttribute { values: &["date", "datetime-local", "time"], default_value: None })],
    },
    Class {
        name: "fs-label",
        title: "Label",
        link: "https://fristil.sobernetics.no/components/label/",
        attributes: &[("data-required", ClassAttribute { values: &["symbol", "text"], default_value: None })],
    },
    Class {
        name: "fs-link",
        title: "Link",
        link: "https://fristil.sobernetics.no/components/link/",
        attributes: &[],
    },
    Class {
        name: "fs-list",
        title: "List",
        link: "https://fristil.sobernetics.no/components/list/",
        attributes: &[("data-variant", ClassAttribute { values: &["plain", "divided"], default_value: Some("default") })],
    },
    Class {
        name: "fs-pagination",
        title: "Pagination",
        link: "https://fristil.sobernetics.no/components/pagination/",
        attributes: &[],
    },
    Class {
        name: "fs-pagination__gap",
        title: "Pagination",
        link: "https://fristil.sobernetics.no/components/pagination/",
        attributes: &[],
    },
    Class {
        name: "fs-paragraph",
        title: "Paragraph",
        link: "https://fristil.sobernetics.no/components/paragraph/",
        attributes: &[("data-variant", ClassAttribute { values: &["lead"], default_value: Some("default") }), ("data-size", ClassAttribute { values: &["small", "large"], default_value: Some("medium") })],
    },
    Class {
        name: "fs-progress",
        title: "Progress",
        link: "https://fristil.sobernetics.no/components/progress/",
        attributes: &[("data-color", ClassAttribute { values: &["success", "warning", "danger"], default_value: None })],
    },
    Class {
        name: "fs-radio",
        title: "Radio",
        link: "https://fristil.sobernetics.no/components/radio/",
        attributes: &[("data-state", ClassAttribute { values: &["invalid", "success"], default_value: Some("default") })],
    },
    Class {
        name: "fs-radio-row",
        title: "Radio",
        link: "https://fristil.sobernetics.no/components/radio/",
        attributes: &[],
    },
    Class {
        name: "fs-search",
        title: "Search",
        link: "https://fristil.sobernetics.no/components/search/",
        attributes: &[("data-state", ClassAttribute { values: &["invalid", "success"], default_value: Some("default") })],
    },
    Class {
        name: "fs-search-row",
        title: "Search",
        link: "https://fristil.sobernetics.no/components/search/",
        attributes: &[],
    },
    Class {
        name: "fs-select",
        title: "Select",
        link: "https://fristil.sobernetics.no/components/select/",
        attributes: &[("data-state", ClassAttribute { values: &["invalid", "success"], default_value: Some("default") }), ("data-picker", ClassAttribute { values: &["styled"], default_value: Some("auto") })],
    },
    Class {
        name: "fs-skeleton",
        title: "Skeleton",
        link: "https://fristil.sobernetics.no/components/skeleton/",
        attributes: &[("data-variant", ClassAttribute { values: &["text", "circle"], default_value: Some("block") })],
    },
    Class {
        name: "fs-skip-link",
        title: "Skip Link",
        link: "https://fristil.sobernetics.no/components/skip-link/",
        attributes: &[],
    },
    Class {
        name: "fs-spinner",
        title: "Spinner",
        link: "https://fristil.sobernetics.no/components/spinner/",
        attributes: &[("data-size", ClassAttribute { values: &["small", "large"], default_value: Some("medium") })],
    },
    Class {
        name: "fs-sr-only",
        title: "Sr Only",
        link: "https://fristil.sobernetics.no/components/sr-only/",
        attributes: &[],
    },
    Class {
        name: "fs-switch",
        title: "Switch",
        link: "https://fristil.sobernetics.no/components/switch/",
        attributes: &[],
    },
    Class {
        name: "fs-switch-row",
        title: "Switch",
        link: "https://fristil.sobernetics.no/components/switch/",
        attributes: &[],
    },
    Class {
        name: "fs-table",
        title: "Table",
        link: "https://fristil.sobernetics.no/components/table/",
        attributes: &[("data-variant", ClassAttribute { values: &["striped"], default_value: Some("default") })],
    },
    Class {
        name: "fs-table__sort",
        title: "Table",
        link: "https://fristil.sobernetics.no/components/table/",
        attributes: &[],
    },
    Class {
        name: "fs-table-scroll",
        title: "Table",
        link: "https://fristil.sobernetics.no/components/table/",
        attributes: &[],
    },
    Class {
        name: "fs-tag",
        title: "Tag",
        link: "https://fristil.sobernetics.no/components/tag/",
        attributes: &[("data-variant", ClassAttribute { values: &["filled"], default_value: Some("outline") })],
    },
    Class {
        name: "fs-textarea",
        title: "Textarea",
        link: "https://fristil.sobernetics.no/components/textarea/",
        attributes: &[("data-state", ClassAttribute { values: &["invalid", "success"], default_value: Some("default") })],
    },
    Class {
        name: "fs-toggle-group",
        title: "Toggle Group",
        link: "https://fristil.sobernetics.no/components/toggle-group/",
        attributes: &[],
    },
    Class {
        name: "fs-toggle-group__option",
        title: "Toggle Group",
        link: "https://fristil.sobernetics.no/components/toggle-group/",
        attributes: &[],
    },
    Class {
        name: "fs-tooltip",
        title: "Tooltip",
        link: "https://fristil.sobernetics.no/components/tooltip/",
        attributes: &[],
    },
    Class {
        name: "fs-tooltip__bubble",
        title: "Tooltip",
        link: "https://fristil.sobernetics.no/components/tooltip/",
        attributes: &[],
    },
    Class {
        name: "fs-dialog",
        title: "Dialog",
        link: "https://fristil.sobernetics.no/components/dialog/",
        attributes: &[],
    },
    Class {
        name: "fs-dialog__body",
        title: "Dialog",
        link: "https://fristil.sobernetics.no/components/dialog/",
        attributes: &[],
    },
    Class {
        name: "fs-dialog__title",
        title: "Dialog",
        link: "https://fristil.sobernetics.no/components/dialog/",
        attributes: &[],
    },
    Class {
        name: "fs-dialog__footer",
        title: "Dialog",
        link: "https://fristil.sobernetics.no/components/dialog/",
        attributes: &[],
    },
    Class {
        name: "fs-dialog__header",
        title: "Dialog",
        link: "https://fristil.sobernetics.no/components/dialog/",
        attributes: &[],
    },
    Class {
        name: "fs-dialog__subtitle",
        title: "Dialog",
        link: "https://fristil.sobernetics.no/components/dialog/",
        attributes: &[],
    },
    Class {
        name: "fs-error-summary",
        title: "Error Summary",
        link: "https://fristil.sobernetics.no/components/error-summary/",
        attributes: &[],
    },
    Class {
        name: "fs-error-summary__title",
        title: "Error Summary",
        link: "https://fristil.sobernetics.no/components/error-summary/",
        attributes: &[],
    },
    Class {
        name: "fs-popover",
        title: "Popover",
        link: "https://fristil.sobernetics.no/components/popover/",
        attributes: &[],
    },
    Class {
        name: "fs-session-timeout",
        title: "Session Timeout",
        link: "https://fristil.sobernetics.no/components/session-timeout/",
        attributes: &[],
    },
    Class {
        name: "fs-session-timeout__dialog",
        title: "Session Timeout",
        link: "https://fristil.sobernetics.no/components/session-timeout/",
        attributes: &[],
    },
    Class {
        name: "fs-session-timeout__title",
        title: "Session Timeout",
        link: "https://fristil.sobernetics.no/components/session-timeout/",
        attributes: &[],
    },
    Class {
        name: "fs-session-timeout__text",
        title: "Session Timeout",
        link: "https://fristil.sobernetics.no/components/session-timeout/",
        attributes: &[],
    },
    Class {
        name: "fs-session-timeout__count",
        title: "Session Timeout",
        link: "https://fristil.sobernetics.no/components/session-timeout/",
        attributes: &[],
    },
    Class {
        name: "fs-session-timeout__actions",
        title: "Session Timeout",
        link: "https://fristil.sobernetics.no/components/session-timeout/",
        attributes: &[],
    },
    Class {
        name: "fs-suggestion__field",
        title: "Suggestion",
        link: "https://fristil.sobernetics.no/components/suggestion/",
        attributes: &[],
    },
    Class {
        name: "fs-suggestion__list",
        title: "Suggestion",
        link: "https://fristil.sobernetics.no/components/suggestion/",
        attributes: &[],
    },
    Class {
        name: "fs-suggestion__option",
        title: "Suggestion",
        link: "https://fristil.sobernetics.no/components/suggestion/",
        attributes: &[],
    },
    Class {
        name: "fs-suggestion__empty",
        title: "Suggestion",
        link: "https://fristil.sobernetics.no/components/suggestion/",
        attributes: &[],
    },
    Class {
        name: "fs-tabs__list",
        title: "Tabs",
        link: "https://fristil.sobernetics.no/components/tabs/",
        attributes: &[],
    },
    Class {
        name: "fs-tabs__panel",
        title: "Tabs",
        link: "https://fristil.sobernetics.no/components/tabs/",
        attributes: &[],
    },
    Class {
        name: "fs-connection-status",
        title: "Connection Status",
        link: "https://fristil.sobernetics.no/components/connection-status/",
        attributes: &[],
    },
    Class {
        name: "fs-connection-status__bar",
        title: "Connection Status",
        link: "https://fristil.sobernetics.no/components/connection-status/",
        attributes: &[],
    },
    Class {
        name: "fs-toast",
        title: "Toast",
        link: "https://fristil.sobernetics.no/components/toast/",
        attributes: &[],
    },
    Class {
        name: "fs-toast__message",
        title: "Toast",
        link: "https://fristil.sobernetics.no/components/toast/",
        attributes: &[],
    },
    Class {
        name: "fs-toast__close",
        title: "Toast",
        link: "https://fristil.sobernetics.no/components/toast/",
        attributes: &[],
    },
    Class {
        name: "fs-theme-control",
        title: "Tilpasning",
        link: "https://fristil.sobernetics.no/tilpasning/",
        attributes: &[],
    },
];
