// Generert av kjerne/scripts/bygg.ts fra classes.ts og elements.ts. Ikke rediger.
use crate::typer::*;

pub static ELEMENTER: &[Element] = &[
    Element {
        tagg: "fs-field",
        lenke: "https://fristil.sobernetics.no/components/field/",
        attributter: &[("invalid", Attributt::Flagg), ("disabled", Attributt::Flagg), ("optional", Attributt::Flagg), ("required-marker", Attributt::Verdier(&["symbol", "text", "none"])), ("control-id", Attributt::Tekst), ("described-by", Attributt::Tekst)],
    },
    Element {
        tagg: "fs-tabs",
        lenke: "https://fristil.sobernetics.no/components/tabs/",
        attributter: &[("server-controlled", Attributt::Flagg)],
    },
    Element {
        tagg: "fs-error-summary",
        lenke: "https://fristil.sobernetics.no/components/error-summary/",
        attributter: &[("data-autofocus", Attributt::Verdier(&["false"])), ("hidden", Attributt::Flagg)],
    },
    Element {
        tagg: "fs-popover",
        lenke: "https://fristil.sobernetics.no/components/popover/",
        attributter: &[("open", Attributt::Flagg), ("placement", Attributt::Verdier(&["bottom-start", "bottom-end", "top-start", "top-end"])), ("server-controlled", Attributt::Flagg)],
    },
    Element {
        tagg: "fs-suggestion",
        lenke: "https://fristil.sobernetics.no/components/suggestion/",
        attributter: &[("prefiltered", Attributt::Flagg), ("count-none", Attributt::Tekst), ("count-zero", Attributt::Tekst), ("count-one", Attributt::Tekst), ("count-two", Attributt::Tekst), ("count-few", Attributt::Tekst), ("count-many", Attributt::Tekst), ("count-other", Attributt::Tekst), ("server-controlled", Attributt::Flagg)],
    },
    Element {
        tagg: "fs-dialog",
        lenke: "https://fristil.sobernetics.no/components/dialog/",
        attributter: &[("open", Attributt::Flagg), ("server-controlled", Attributt::Flagg)],
    },
    Element {
        tagg: "fs-toast",
        lenke: "https://fristil.sobernetics.no/components/toast/",
        attributter: &[("duration", Attributt::Tall), ("label", Attributt::Tekst), ("close-label", Attributt::Tekst)],
    },
    Element {
        tagg: "fs-session-timeout",
        lenke: "https://fristil.sobernetics.no/components/session-timeout/",
        attributter: &[("warn-at", Attributt::Tall), ("expires-at", Attributt::Tall)],
    },
    Element {
        tagg: "fs-connection-status",
        lenke: "https://fristil.sobernetics.no/components/connection-status/",
        attributter: &[("offline-text", Attributt::Tekst), ("online-text", Attributt::Tekst)],
    },
];

pub static KLASSER: &[Klasse] = &[
    Klasse {
        navn: "fs-accordion",
        tittel: "Accordion",
        lenke: "https://fristil.sobernetics.no/components/accordion/",
        attributter: &[("data-variant", KlasseAttributt { verdier: &["plain"], standard: Some("default") })],
    },
    Klasse {
        navn: "fs-accordion__content",
        tittel: "Accordion",
        lenke: "https://fristil.sobernetics.no/components/accordion/",
        attributter: &[],
    },
    Klasse {
        navn: "fs-alert",
        tittel: "Alert",
        lenke: "https://fristil.sobernetics.no/components/alert/",
        attributter: &[("data-color", KlasseAttributt { verdier: &["info", "success", "warning", "danger"], standard: None })],
    },
    Klasse {
        navn: "fs-alert__title",
        tittel: "Alert",
        lenke: "https://fristil.sobernetics.no/components/alert/",
        attributter: &[],
    },
    Klasse {
        navn: "fs-avatar",
        tittel: "Avatar",
        lenke: "https://fristil.sobernetics.no/components/avatar/",
        attributter: &[("data-variant", KlasseAttributt { verdier: &["square"], standard: Some("circle") }), ("data-size", KlasseAttributt { verdier: &["small", "large"], standard: Some("medium") })],
    },
    Klasse {
        navn: "fs-avatar-stack",
        tittel: "Avatar",
        lenke: "https://fristil.sobernetics.no/components/avatar/",
        attributter: &[],
    },
    Klasse {
        navn: "fs-badge",
        tittel: "Badge",
        lenke: "https://fristil.sobernetics.no/components/badge/",
        attributter: &[("data-color", KlasseAttributt { verdier: &["success", "warning", "danger", "neutral"], standard: Some("info") })],
    },
    Klasse {
        navn: "fs-breadcrumbs",
        tittel: "Breadcrumbs",
        lenke: "https://fristil.sobernetics.no/components/breadcrumbs/",
        attributter: &[],
    },
    Klasse {
        navn: "fs-button",
        tittel: "Button",
        lenke: "https://fristil.sobernetics.no/components/button/",
        attributter: &[("data-variant", KlasseAttributt { verdier: &["secondary", "ghost", "danger"], standard: Some("primary") })],
    },
    Klasse {
        navn: "fs-card",
        tittel: "Card",
        lenke: "https://fristil.sobernetics.no/components/card/",
        attributter: &[("data-variant", KlasseAttributt { verdier: &["filled"], standard: Some("outline") })],
    },
    Klasse {
        navn: "fs-card__title",
        tittel: "Card",
        lenke: "https://fristil.sobernetics.no/components/card/",
        attributter: &[],
    },
    Klasse {
        navn: "fs-checkbox",
        tittel: "Checkbox",
        lenke: "https://fristil.sobernetics.no/components/checkbox/",
        attributter: &[("data-state", KlasseAttributt { verdier: &["invalid", "success"], standard: Some("default") })],
    },
    Klasse {
        navn: "fs-checkbox-row",
        tittel: "Checkbox",
        lenke: "https://fristil.sobernetics.no/components/checkbox/",
        attributter: &[],
    },
    Klasse {
        navn: "fs-divider",
        tittel: "Divider",
        lenke: "https://fristil.sobernetics.no/components/divider/",
        attributter: &[("data-variant", KlasseAttributt { verdier: &["subtle", "strong"], standard: Some("default") })],
    },
    Klasse {
        navn: "fs-error-text",
        tittel: "Error Text",
        lenke: "https://fristil.sobernetics.no/components/error-text/",
        attributter: &[("data-variant", KlasseAttributt { verdier: &["warning"], standard: Some("error") })],
    },
    Klasse {
        navn: "fs-fieldset",
        tittel: "Fieldset",
        lenke: "https://fristil.sobernetics.no/components/fieldset/",
        attributter: &[("data-state", KlasseAttributt { verdier: &["invalid", "success"], standard: Some("default") })],
    },
    Klasse {
        navn: "fs-legend",
        tittel: "Fieldset",
        lenke: "https://fristil.sobernetics.no/components/fieldset/",
        attributter: &[("data-required", KlasseAttributt { verdier: &["symbol", "text"], standard: None })],
    },
    Klasse {
        navn: "fs-file-upload",
        tittel: "File Upload",
        lenke: "https://fristil.sobernetics.no/components/file-upload/",
        attributter: &[("data-state", KlasseAttributt { verdier: &["invalid", "success"], standard: Some("default") })],
    },
    Klasse {
        navn: "fs-file-upload-list",
        tittel: "File Upload",
        lenke: "https://fristil.sobernetics.no/components/file-upload/",
        attributter: &[],
    },
    Klasse {
        navn: "fs-heading",
        tittel: "Heading",
        lenke: "https://fristil.sobernetics.no/components/heading/",
        attributter: &[("data-size", KlasseAttributt { verdier: &["xs", "s", "m", "xl", "mega"], standard: Some("l") })],
    },
    Klasse {
        navn: "fs-help-text",
        tittel: "Help Text",
        lenke: "https://fristil.sobernetics.no/components/help-text/",
        attributter: &[("data-variant", KlasseAttributt { verdier: &["strong", "success", "warning"], standard: Some("muted") })],
    },
    Klasse {
        navn: "fs-input",
        tittel: "Input",
        lenke: "https://fristil.sobernetics.no/components/input/",
        attributter: &[("data-state", KlasseAttributt { verdier: &["invalid", "success"], standard: Some("default") }), ("data-variant", KlasseAttributt { verdier: &["date", "datetime-local", "time"], standard: None })],
    },
    Klasse {
        navn: "fs-label",
        tittel: "Label",
        lenke: "https://fristil.sobernetics.no/components/label/",
        attributter: &[("data-required", KlasseAttributt { verdier: &["symbol", "text"], standard: None })],
    },
    Klasse {
        navn: "fs-link",
        tittel: "Link",
        lenke: "https://fristil.sobernetics.no/components/link/",
        attributter: &[],
    },
    Klasse {
        navn: "fs-list",
        tittel: "List",
        lenke: "https://fristil.sobernetics.no/components/list/",
        attributter: &[("data-variant", KlasseAttributt { verdier: &["plain", "divided"], standard: Some("default") })],
    },
    Klasse {
        navn: "fs-pagination",
        tittel: "Pagination",
        lenke: "https://fristil.sobernetics.no/components/pagination/",
        attributter: &[],
    },
    Klasse {
        navn: "fs-pagination__gap",
        tittel: "Pagination",
        lenke: "https://fristil.sobernetics.no/components/pagination/",
        attributter: &[],
    },
    Klasse {
        navn: "fs-paragraph",
        tittel: "Paragraph",
        lenke: "https://fristil.sobernetics.no/components/paragraph/",
        attributter: &[("data-variant", KlasseAttributt { verdier: &["lead"], standard: Some("default") }), ("data-size", KlasseAttributt { verdier: &["small", "large"], standard: Some("medium") })],
    },
    Klasse {
        navn: "fs-progress",
        tittel: "Progress",
        lenke: "https://fristil.sobernetics.no/components/progress/",
        attributter: &[("data-color", KlasseAttributt { verdier: &["success", "warning", "danger"], standard: None })],
    },
    Klasse {
        navn: "fs-radio",
        tittel: "Radio",
        lenke: "https://fristil.sobernetics.no/components/radio/",
        attributter: &[("data-state", KlasseAttributt { verdier: &["invalid", "success"], standard: Some("default") })],
    },
    Klasse {
        navn: "fs-radio-row",
        tittel: "Radio",
        lenke: "https://fristil.sobernetics.no/components/radio/",
        attributter: &[],
    },
    Klasse {
        navn: "fs-search",
        tittel: "Search",
        lenke: "https://fristil.sobernetics.no/components/search/",
        attributter: &[("data-state", KlasseAttributt { verdier: &["invalid", "success"], standard: Some("default") })],
    },
    Klasse {
        navn: "fs-search-row",
        tittel: "Search",
        lenke: "https://fristil.sobernetics.no/components/search/",
        attributter: &[],
    },
    Klasse {
        navn: "fs-select",
        tittel: "Select",
        lenke: "https://fristil.sobernetics.no/components/select/",
        attributter: &[("data-state", KlasseAttributt { verdier: &["invalid", "success"], standard: Some("default") }), ("data-picker", KlasseAttributt { verdier: &["styled"], standard: Some("auto") })],
    },
    Klasse {
        navn: "fs-skeleton",
        tittel: "Skeleton",
        lenke: "https://fristil.sobernetics.no/components/skeleton/",
        attributter: &[("data-variant", KlasseAttributt { verdier: &["text", "circle"], standard: Some("block") })],
    },
    Klasse {
        navn: "fs-skip-link",
        tittel: "Skip Link",
        lenke: "https://fristil.sobernetics.no/components/skip-link/",
        attributter: &[],
    },
    Klasse {
        navn: "fs-spinner",
        tittel: "Spinner",
        lenke: "https://fristil.sobernetics.no/components/spinner/",
        attributter: &[("data-size", KlasseAttributt { verdier: &["small", "large"], standard: Some("medium") })],
    },
    Klasse {
        navn: "fs-sr-only",
        tittel: "Sr Only",
        lenke: "https://fristil.sobernetics.no/components/sr-only/",
        attributter: &[],
    },
    Klasse {
        navn: "fs-switch",
        tittel: "Switch",
        lenke: "https://fristil.sobernetics.no/components/switch/",
        attributter: &[],
    },
    Klasse {
        navn: "fs-switch-row",
        tittel: "Switch",
        lenke: "https://fristil.sobernetics.no/components/switch/",
        attributter: &[],
    },
    Klasse {
        navn: "fs-table",
        tittel: "Table",
        lenke: "https://fristil.sobernetics.no/components/table/",
        attributter: &[("data-variant", KlasseAttributt { verdier: &["striped"], standard: Some("default") })],
    },
    Klasse {
        navn: "fs-table__sort",
        tittel: "Table",
        lenke: "https://fristil.sobernetics.no/components/table/",
        attributter: &[],
    },
    Klasse {
        navn: "fs-table-scroll",
        tittel: "Table",
        lenke: "https://fristil.sobernetics.no/components/table/",
        attributter: &[],
    },
    Klasse {
        navn: "fs-tag",
        tittel: "Tag",
        lenke: "https://fristil.sobernetics.no/components/tag/",
        attributter: &[("data-variant", KlasseAttributt { verdier: &["filled"], standard: Some("outline") })],
    },
    Klasse {
        navn: "fs-textarea",
        tittel: "Textarea",
        lenke: "https://fristil.sobernetics.no/components/textarea/",
        attributter: &[("data-state", KlasseAttributt { verdier: &["invalid", "success"], standard: Some("default") })],
    },
    Klasse {
        navn: "fs-toggle-group",
        tittel: "Toggle Group",
        lenke: "https://fristil.sobernetics.no/components/toggle-group/",
        attributter: &[],
    },
    Klasse {
        navn: "fs-toggle-group__option",
        tittel: "Toggle Group",
        lenke: "https://fristil.sobernetics.no/components/toggle-group/",
        attributter: &[],
    },
    Klasse {
        navn: "fs-tooltip",
        tittel: "Tooltip",
        lenke: "https://fristil.sobernetics.no/components/tooltip/",
        attributter: &[],
    },
    Klasse {
        navn: "fs-tooltip__bubble",
        tittel: "Tooltip",
        lenke: "https://fristil.sobernetics.no/components/tooltip/",
        attributter: &[],
    },
    Klasse {
        navn: "fs-dialog",
        tittel: "Dialog",
        lenke: "https://fristil.sobernetics.no/components/dialog/",
        attributter: &[],
    },
    Klasse {
        navn: "fs-dialog__body",
        tittel: "Dialog",
        lenke: "https://fristil.sobernetics.no/components/dialog/",
        attributter: &[],
    },
    Klasse {
        navn: "fs-dialog__title",
        tittel: "Dialog",
        lenke: "https://fristil.sobernetics.no/components/dialog/",
        attributter: &[],
    },
    Klasse {
        navn: "fs-dialog__footer",
        tittel: "Dialog",
        lenke: "https://fristil.sobernetics.no/components/dialog/",
        attributter: &[],
    },
    Klasse {
        navn: "fs-dialog__header",
        tittel: "Dialog",
        lenke: "https://fristil.sobernetics.no/components/dialog/",
        attributter: &[],
    },
    Klasse {
        navn: "fs-dialog__subtitle",
        tittel: "Dialog",
        lenke: "https://fristil.sobernetics.no/components/dialog/",
        attributter: &[],
    },
    Klasse {
        navn: "fs-error-summary",
        tittel: "Error Summary",
        lenke: "https://fristil.sobernetics.no/components/error-summary/",
        attributter: &[],
    },
    Klasse {
        navn: "fs-error-summary__title",
        tittel: "Error Summary",
        lenke: "https://fristil.sobernetics.no/components/error-summary/",
        attributter: &[],
    },
    Klasse {
        navn: "fs-popover",
        tittel: "Popover",
        lenke: "https://fristil.sobernetics.no/components/popover/",
        attributter: &[],
    },
    Klasse {
        navn: "fs-session-timeout",
        tittel: "Session Timeout",
        lenke: "https://fristil.sobernetics.no/components/session-timeout/",
        attributter: &[],
    },
    Klasse {
        navn: "fs-session-timeout__dialog",
        tittel: "Session Timeout",
        lenke: "https://fristil.sobernetics.no/components/session-timeout/",
        attributter: &[],
    },
    Klasse {
        navn: "fs-session-timeout__title",
        tittel: "Session Timeout",
        lenke: "https://fristil.sobernetics.no/components/session-timeout/",
        attributter: &[],
    },
    Klasse {
        navn: "fs-session-timeout__text",
        tittel: "Session Timeout",
        lenke: "https://fristil.sobernetics.no/components/session-timeout/",
        attributter: &[],
    },
    Klasse {
        navn: "fs-session-timeout__count",
        tittel: "Session Timeout",
        lenke: "https://fristil.sobernetics.no/components/session-timeout/",
        attributter: &[],
    },
    Klasse {
        navn: "fs-session-timeout__actions",
        tittel: "Session Timeout",
        lenke: "https://fristil.sobernetics.no/components/session-timeout/",
        attributter: &[],
    },
    Klasse {
        navn: "fs-suggestion__field",
        tittel: "Suggestion",
        lenke: "https://fristil.sobernetics.no/components/suggestion/",
        attributter: &[],
    },
    Klasse {
        navn: "fs-suggestion__list",
        tittel: "Suggestion",
        lenke: "https://fristil.sobernetics.no/components/suggestion/",
        attributter: &[],
    },
    Klasse {
        navn: "fs-suggestion__option",
        tittel: "Suggestion",
        lenke: "https://fristil.sobernetics.no/components/suggestion/",
        attributter: &[],
    },
    Klasse {
        navn: "fs-suggestion__empty",
        tittel: "Suggestion",
        lenke: "https://fristil.sobernetics.no/components/suggestion/",
        attributter: &[],
    },
    Klasse {
        navn: "fs-tabs__list",
        tittel: "Tabs",
        lenke: "https://fristil.sobernetics.no/components/tabs/",
        attributter: &[],
    },
    Klasse {
        navn: "fs-tabs__panel",
        tittel: "Tabs",
        lenke: "https://fristil.sobernetics.no/components/tabs/",
        attributter: &[],
    },
    Klasse {
        navn: "fs-connection-status",
        tittel: "Connection Status",
        lenke: "https://fristil.sobernetics.no/components/connection-status/",
        attributter: &[],
    },
    Klasse {
        navn: "fs-connection-status__bar",
        tittel: "Connection Status",
        lenke: "https://fristil.sobernetics.no/components/connection-status/",
        attributter: &[],
    },
    Klasse {
        navn: "fs-toast",
        tittel: "Toast",
        lenke: "https://fristil.sobernetics.no/components/toast/",
        attributter: &[],
    },
    Klasse {
        navn: "fs-toast__message",
        tittel: "Toast",
        lenke: "https://fristil.sobernetics.no/components/toast/",
        attributter: &[],
    },
    Klasse {
        navn: "fs-toast__close",
        tittel: "Toast",
        lenke: "https://fristil.sobernetics.no/components/toast/",
        attributter: &[],
    },
    Klasse {
        navn: "fs-theme-control",
        tittel: "Tilpasning",
        lenke: "https://fristil.sobernetics.no/tilpasning/",
        attributter: &[],
    },
];
