// Generert av editor/scripts/generate.ts. Ikke rediger.
package no.fristil.intellij

/** Klassene Fristil sender ut, lest fra pakken da fila ble generert. */
internal val KLASSER: List<Klasse> =
  listOf(
    Klasse("fs-accordion", "Accordion", "Panel som kan foldes ut, bygget på details og summary. CSS-komponent med to klasser og ingen JavaScript.", "https://fristil.netlify.app/components/accordion/"),
    Klasse("fs-accordion__content", "Accordion", "Panel som kan foldes ut, bygget på details og summary. CSS-komponent med to klasser og ingen JavaScript.", "https://fristil.netlify.app/components/accordion/"),
    Klasse("fs-alert", "Alert", "Melding som gjelder hele siden eller hele skjemaet. CSS-komponent med to klasser og ingen JavaScript.", "https://fristil.netlify.app/components/alert/"),
    Klasse("fs-alert__title", "Alert", "Melding som gjelder hele siden eller hele skjemaet. CSS-komponent med to klasser og ingen JavaScript.", "https://fristil.netlify.app/components/alert/"),
    Klasse("fs-avatar", "Avatar", "Profilbilde eller initialer. CSS-komponent med to klasser og ingen JavaScript.", "https://fristil.netlify.app/components/avatar/"),
    Klasse("fs-avatar-stack", "Avatar", "Profilbilde eller initialer. CSS-komponent med to klasser og ingen JavaScript.", "https://fristil.netlify.app/components/avatar/"),
    Klasse("fs-badge", "Badge", "Kompakt statusmerke. CSS-komponent med én klasse og ingen JavaScript.", "https://fristil.netlify.app/components/badge/"),
    Klasse("fs-breadcrumbs", "Breadcrumbs", "Brødsmulesti som viser hvor på siden brukeren er. CSS-komponent med én klasse og ingen JavaScript.", "https://fristil.netlify.app/components/breadcrumbs/"),
    Klasse("fs-button", "Button", "Knapp for handlinger. CSS-komponent med én klasse og ingen JavaScript.", "https://fristil.netlify.app/components/button/"),
    Klasse("fs-card", "Card", "Boks som samler innhold som hører sammen. CSS-komponent med to klasser og ingen JavaScript.", "https://fristil.netlify.app/components/card/"),
    Klasse("fs-card__title", "Card", "Boks som samler innhold som hører sammen. CSS-komponent med to klasser og ingen JavaScript.", "https://fristil.netlify.app/components/card/"),
    Klasse("fs-checkbox", "Checkbox", "Avkryssingsboks for valg som står for seg selv. CSS-komponent med to klasser og ingen JavaScript.", "https://fristil.netlify.app/components/checkbox/"),
    Klasse("fs-checkbox-row", "Checkbox", "Avkryssingsboks for valg som står for seg selv. CSS-komponent med to klasser og ingen JavaScript.", "https://fristil.netlify.app/components/checkbox/"),
    Klasse("fs-divider", "Divider", "Skillelinje mellom deler av innholdet. CSS-komponent med én klasse og ingen JavaScript.", "https://fristil.netlify.app/components/divider/"),
    Klasse("fs-error-text", "Error Text", "Feilmelding under et skjemafelt. CSS-komponent med én klasse og ingen JavaScript.", "https://fristil.netlify.app/components/error-text/"),
    Klasse("fs-fieldset", "Fieldset", "Gruppe av kontroller med en felles ledetekst. CSS-komponent med to klasser og ingen JavaScript.", "https://fristil.netlify.app/components/fieldset/"),
    Klasse("fs-legend", "Fieldset", "Gruppe av kontroller med en felles ledetekst. CSS-komponent med to klasser og ingen JavaScript.", "https://fristil.netlify.app/components/fieldset/"),
    Klasse("fs-file-upload", "File Upload", "Felt for opplasting av filer. CSS-komponent med to klasser og ingen JavaScript.", "https://fristil.netlify.app/components/file-upload/"),
    Klasse("fs-file-upload-list", "File Upload", "Felt for opplasting av filer. CSS-komponent med to klasser og ingen JavaScript.", "https://fristil.netlify.app/components/file-upload/"),
    Klasse("fs-heading", "Heading", "Overskrifter i seks størrelser, uavhengig av nivå. CSS-komponent med én klasse og ingen JavaScript.", "https://fristil.netlify.app/components/heading/"),
    Klasse("fs-help-text", "Help Text", "Forklarende tekst under et skjemafelt. CSS-komponent med én klasse og ingen JavaScript.", "https://fristil.netlify.app/components/help-text/"),
    Klasse("fs-input", "Input", "Tekstfelt for skjema, med tilstander for gyldig og ugyldig. CSS-komponent.", "https://fristil.netlify.app/components/input/"),
    Klasse("fs-label", "Label", "Ledetekst for skjemafelt, med markering av påkrevd og valgfritt. CSS-komponent.", "https://fristil.netlify.app/components/label/"),
    Klasse("fs-link", "Link", "Lenkestil for navigasjon i løpende tekst. CSS-komponent med én klasse og ingen JavaScript.", "https://fristil.netlify.app/components/link/"),
    Klasse("fs-list", "List", "Punktliste, nummerert liste og lister uten punkter. CSS-komponent med én klasse og ingen JavaScript.", "https://fristil.netlify.app/components/list/"),
    Klasse("fs-pagination", "Pagination", "Sidenavigering for lange lister. CSS-komponent med to klasser og ingen JavaScript.", "https://fristil.netlify.app/components/pagination/"),
    Klasse("fs-pagination__gap", "Pagination", "Sidenavigering for lange lister. CSS-komponent med to klasser og ingen JavaScript.", "https://fristil.netlify.app/components/pagination/"),
    Klasse("fs-paragraph", "Paragraph", "Brødtekst og ingress med begrenset linjelengde. CSS-komponent med én klasse og ingen JavaScript.", "https://fristil.netlify.app/components/paragraph/"),
    Klasse("fs-radio", "Radio", "Radioknapper for ett valg blant flere. CSS-komponent med to klasser og ingen JavaScript.", "https://fristil.netlify.app/components/radio/"),
    Klasse("fs-radio-row", "Radio", "Radioknapper for ett valg blant flere. CSS-komponent med to klasser og ingen JavaScript.", "https://fristil.netlify.app/components/radio/"),
    Klasse("fs-search", "Search", "Søkefelt med forstørrelsesglass. CSS-komponent med to klasser og ingen JavaScript.", "https://fristil.netlify.app/components/search/"),
    Klasse("fs-search-row", "Search", "Søkefelt med forstørrelsesglass. CSS-komponent med to klasser og ingen JavaScript.", "https://fristil.netlify.app/components/search/"),
    Klasse("fs-select", "Select", "Nedtrekksliste. CSS-komponent med én klasse og ingen JavaScript.", "https://fristil.netlify.app/components/select/"),
    Klasse("fs-skeleton", "Skeleton", "Plassholder som viser formen på innhold som lastes. CSS-komponent med én klasse og ingen JavaScript.", "https://fristil.netlify.app/components/skeleton/"),
    Klasse("fs-skip-link", "Skip Link", "Lenke som hopper forbi menyen til hovedinnholdet. CSS-komponent med én klasse og ingen JavaScript.", "https://fristil.netlify.app/components/skip-link/"),
    Klasse("fs-spinner", "Spinner", "Venteindikator for noe som pågår. CSS-komponent med én klasse og ingen JavaScript.", "https://fristil.netlify.app/components/spinner/"),
    Klasse("fs-sr-only", "Sr Only", "Tekst som bare skjermlesere får. CSS-komponent med én klasse og ingen JavaScript.", "https://fristil.netlify.app/components/sr-only/"),
    Klasse("fs-switch", "Switch", "Bryter for en innstilling som slår inn med en gang. CSS-komponent med to klasser og ingen JavaScript.", "https://fristil.netlify.app/components/switch/"),
    Klasse("fs-switch-row", "Switch", "Bryter for en innstilling som slår inn med en gang. CSS-komponent med to klasser og ingen JavaScript.", "https://fristil.netlify.app/components/switch/"),
    Klasse("fs-table", "Table", "Tabell for data i rader og kolonner. CSS-komponent med to klasser og ingen JavaScript.", "https://fristil.netlify.app/components/table/"),
    Klasse("fs-table-scroll", "Table", "Tabell for data i rader og kolonner. CSS-komponent med to klasser og ingen JavaScript.", "https://fristil.netlify.app/components/table/"),
    Klasse("fs-tag", "Tag", "Merkelapp for emneord og filtre. CSS-komponent med én klasse og ingen JavaScript.", "https://fristil.netlify.app/components/tag/"),
    Klasse("fs-textarea", "Textarea", "Flerlinjet tekstfelt. CSS-komponent med én klasse og ingen JavaScript.", "https://fristil.netlify.app/components/textarea/"),
    Klasse("fs-toggle-group", "Toggle Group", "Gruppe der ett alternativ er valgt om gangen. CSS-komponent med to klasser og ingen JavaScript.", "https://fristil.netlify.app/components/toggle-group/"),
    Klasse("fs-toggle-group__option", "Toggle Group", "Gruppe der ett alternativ er valgt om gangen. CSS-komponent med to klasser og ingen JavaScript.", "https://fristil.netlify.app/components/toggle-group/"),
    Klasse("fs-tooltip", "Tooltip", "Liten hjelpetekst som vises på hover og fokus. CSS-komponent med to klasser og ingen JavaScript.", "https://fristil.netlify.app/components/tooltip/"),
    Klasse("fs-tooltip__bubble", "Tooltip", "Liten hjelpetekst som vises på hover og fokus. CSS-komponent med to klasser og ingen JavaScript.", "https://fristil.netlify.app/components/tooltip/"),
    Klasse("fs-dialog", "Dialog", "Modal dialog bygget på det native dialog-elementet. Seks klasser og ingen JavaScript, med en valgfri komponent for servere som ikke kan kalle showModal().", "https://fristil.netlify.app/components/dialog/"),
    Klasse("fs-dialog__body", "Dialog", "Modal dialog bygget på det native dialog-elementet. Seks klasser og ingen JavaScript, med en valgfri komponent for servere som ikke kan kalle showModal().", "https://fristil.netlify.app/components/dialog/"),
    Klasse("fs-dialog__title", "Dialog", "Modal dialog bygget på det native dialog-elementet. Seks klasser og ingen JavaScript, med en valgfri komponent for servere som ikke kan kalle showModal().", "https://fristil.netlify.app/components/dialog/"),
    Klasse("fs-dialog__footer", "Dialog", "Modal dialog bygget på det native dialog-elementet. Seks klasser og ingen JavaScript, med en valgfri komponent for servere som ikke kan kalle showModal().", "https://fristil.netlify.app/components/dialog/"),
    Klasse("fs-dialog__header", "Dialog", "Modal dialog bygget på det native dialog-elementet. Seks klasser og ingen JavaScript, med en valgfri komponent for servere som ikke kan kalle showModal().", "https://fristil.netlify.app/components/dialog/"),
    Klasse("fs-dialog__subtitle", "Dialog", "Modal dialog bygget på det native dialog-elementet. Seks klasser og ingen JavaScript, med en valgfri komponent for servere som ikke kan kalle showModal().", "https://fristil.netlify.app/components/dialog/"),
    Klasse("fs-error-summary", "Error Summary", "Samler feilene i et skjema og sender brukeren til feltet som feilet. Rammekomponent.", "https://fristil.netlify.app/components/error-summary/"),
    Klasse("fs-error-summary__title", "Error Summary", "Samler feilene i et skjema og sender brukeren til feltet som feilet. Rammekomponent.", "https://fristil.netlify.app/components/error-summary/"),
    Klasse("fs-popover", "Popover", "Panel som henger under en knapp og lukker seg selv. Rammekomponent.", "https://fristil.netlify.app/components/popover/"),
    Klasse("fs-suggestion__field", "Suggestion", "Felt med forslagsliste som snevrer seg inn mens brukeren skriver. Rammekomponent.", "https://fristil.netlify.app/components/suggestion/"),
    Klasse("fs-suggestion__list", "Suggestion", "Felt med forslagsliste som snevrer seg inn mens brukeren skriver. Rammekomponent.", "https://fristil.netlify.app/components/suggestion/"),
    Klasse("fs-suggestion__option", "Suggestion", "Felt med forslagsliste som snevrer seg inn mens brukeren skriver. Rammekomponent.", "https://fristil.netlify.app/components/suggestion/"),
    Klasse("fs-suggestion__empty", "Suggestion", "Felt med forslagsliste som snevrer seg inn mens brukeren skriver. Rammekomponent.", "https://fristil.netlify.app/components/suggestion/"),
    Klasse("fs-tabs__list", "Tabs", "Fanerad koblet til panelene sine. Rammekomponent.", "https://fristil.netlify.app/components/tabs/"),
    Klasse("fs-tabs__panel", "Tabs", "Fanerad koblet til panelene sine. Rammekomponent.", "https://fristil.netlify.app/components/tabs/"),
    Klasse("fs-connection-status", "Connection Status", "Sier fra når forbindelsen til serveren er borte. Frittstående komponent.", "https://fristil.netlify.app/components/connection-status/"),
    Klasse("fs-connection-status__bar", "Connection Status", "Sier fra når forbindelsen til serveren er borte. Frittstående komponent.", "https://fristil.netlify.app/components/connection-status/"),
    Klasse("fs-session-timeout", "Session Timeout", "Varsler før en innlogget økt går ut, og teller ned. Frittstående komponent.", "https://fristil.netlify.app/components/session-timeout/"),
    Klasse("fs-session-timeout__dialog", "Session Timeout", "Varsler før en innlogget økt går ut, og teller ned. Frittstående komponent.", "https://fristil.netlify.app/components/session-timeout/"),
    Klasse("fs-session-timeout__title", "Session Timeout", "Varsler før en innlogget økt går ut, og teller ned. Frittstående komponent.", "https://fristil.netlify.app/components/session-timeout/"),
    Klasse("fs-session-timeout__text", "Session Timeout", "Varsler før en innlogget økt går ut, og teller ned. Frittstående komponent.", "https://fristil.netlify.app/components/session-timeout/"),
    Klasse("fs-session-timeout__count", "Session Timeout", "Varsler før en innlogget økt går ut, og teller ned. Frittstående komponent.", "https://fristil.netlify.app/components/session-timeout/"),
    Klasse("fs-session-timeout__actions", "Session Timeout", "Varsler før en innlogget økt går ut, og teller ned. Frittstående komponent.", "https://fristil.netlify.app/components/session-timeout/"),
    Klasse("fs-toast", "Toast", "Kø av korte meldinger i hjørnet av skjermen. Frittstående komponent.", "https://fristil.netlify.app/components/toast/"),
    Klasse("fs-toast__close", "Toast", "Kø av korte meldinger i hjørnet av skjermen. Frittstående komponent.", "https://fristil.netlify.app/components/toast/"),
    Klasse("fs-theme-control", "Tilpasning", "Endre farger, form og størrelse i Fristil uten at endringene forsvinner ved neste oppgradering.", "https://fristil.netlify.app/tilpasning/"),
  )
