import startlight from "@astrojs/starlight"
import tailwindcss from "@tailwindcss/vite"
import { defineConfig } from "astro/config"
import remarkGfm from "remark-gfm"

// https://astro.build/config
export default defineConfig({
  markdown: {
    remarkPlugins: [remarkGfm],
  },
  vite: {
    plugins: [tailwindcss()],
  },
  integrations: [
    startlight({
      title: "Fristil - Dokumentasjon",
      defaultLocale: "root",
      locales: {
        root: { label: "Norsk", lang: "nb" },
      },
      components: {
        SiteTitle: "./src/components/SiteTitle.astro",
      },
      customCss: [
        "./src/styles/global.css",
        "@fristil/designsystem/tokens.css",
        "@fristil/designsystem/file-upload.css",
        "@fristil/designsystem/popover.css",
        "@fristil/designsystem/toast.css",
        "@fristil/designsystem/suggestion.css",
        "@fristil/designsystem/tabs.css",
        "@fristil/designsystem/error-summary.css",
        "@fristil/designsystem/paragraph.css",
        "@fristil/designsystem/heading.css",
        "@fristil/designsystem/tooltip.css",
        "@fristil/designsystem/toggle-group.css",
        "@fristil/designsystem/search.css",
        "@fristil/designsystem/dialog.css",
        "@fristil/designsystem/accordion.css",
        "@fristil/designsystem/skip-link.css",
        "@fristil/designsystem/pagination.css",
        "@fristil/designsystem/breadcrumbs.css",
        "@fristil/designsystem/skeleton.css",
        "@fristil/designsystem/avatar.css",
        "@fristil/designsystem/tag.css",
        "@fristil/designsystem/list.css",
        "@fristil/designsystem/table.css",
        "@fristil/designsystem/button.css",
        "@fristil/designsystem/link.css",
        "@fristil/designsystem/badge.css",
        "@fristil/designsystem/label.css",
        "@fristil/designsystem/input.css",
        "@fristil/designsystem/textarea.css",
        "@fristil/designsystem/select.css",
        "@fristil/designsystem/help-text.css",
        "@fristil/designsystem/error-text.css",
        "@fristil/designsystem/sr-only.css",
        "@fristil/designsystem/checkbox.css",
        "@fristil/designsystem/radio.css",
        "@fristil/designsystem/switch.css",
        "@fristil/designsystem/fieldset.css",
        "@fristil/designsystem/alert.css",
        "@fristil/designsystem/card.css",
        "@fristil/designsystem/divider.css",
        "@fristil/designsystem/spinner.css",
        "@fristil/designsystem/field.css",
        "@fristil/designsystem/date-field.css",
      ],
      sidebar: [
        {
          label: "Start her",
          items: [
            { label: "Introduksjon", slug: "introduksjon" },
            { label: "Kom i gang", slug: "kom-i-gang" },
            { label: "Rammeverk", slug: "rammeverk" },
            { label: "Design tokens", slug: "design-tokens" },
            { label: "Tilpasning", slug: "tilpasning" },
            { label: "Tailwind", slug: "tailwind" },
            { label: "Typesikker bruk", slug: "typesikker-bruk" },
          ],
        },
        {
          label: "Komponenter",
          items: [
            {
              label: "CSS-komponenter",
              items: [
                { label: "Button", slug: "components/button" },
                { label: "Heading", slug: "components/heading" },
                { label: "Paragraph", slug: "components/paragraph" },
                { label: "Link", slug: "components/link" },
                { label: "Badge", slug: "components/badge" },
                { label: "Alert", slug: "components/alert" },
                { label: "Card", slug: "components/card" },
                { label: "Divider", slug: "components/divider" },
                { label: "Spinner", slug: "components/spinner" },
                { label: "Table", slug: "components/table" },
                { label: "List", slug: "components/list" },
                { label: "Tag", slug: "components/tag" },
                { label: "Avatar", slug: "components/avatar" },
                { label: "Skeleton", slug: "components/skeleton" },
                { label: "Breadcrumbs", slug: "components/breadcrumbs" },
                { label: "Pagination", slug: "components/pagination" },
                { label: "Skip Link", slug: "components/skip-link" },
                { label: "Accordion", slug: "components/accordion" },
                { label: "Dialog", slug: "components/dialog" },
                { label: "Tooltip", slug: "components/tooltip" },
                { label: "Label", slug: "components/label" },
                { label: "Input", slug: "components/input" },
                { label: "Textarea", slug: "components/textarea" },
                { label: "Select", slug: "components/select" },
                { label: "Checkbox", slug: "components/checkbox" },
                { label: "Radio", slug: "components/radio" },
                { label: "Switch", slug: "components/switch" },
                { label: "Fieldset", slug: "components/fieldset" },
                { label: "Search", slug: "components/search" },
                { label: "File Upload", slug: "components/file-upload" },
                { label: "Toggle Group", slug: "components/toggle-group" },
                { label: "Help Text", slug: "components/help-text" },
                { label: "Error Text", slug: "components/error-text" },
                { label: "Sr Only", slug: "components/sr-only" },
              ],
            },
            {
              label: "Ramme",
              items: [
                { label: "Field", slug: "components/field" },
                { label: "Tabs", slug: "components/tabs" },
                { label: "Error Summary", slug: "components/error-summary" },
                { label: "Popover", slug: "components/popover" },
              ],
            },
            {
              label: "Frittstående",
              items: [
                { label: "Date Field", slug: "components/date-field" },
                { label: "Calendar", slug: "components/calendar" },
                { label: "Toast", slug: "components/toast" },
                { label: "Suggestion", slug: "components/suggestion" },
              ],
            },
          ],
        },
      ],
    }),
  ],
})
